// dart format width=80
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:bazario/app/app_router.dart';
import 'data/repositories/home_provider.dart';
import 'package:firebase_core/firebase_core.dart'; // Import the Firebase Core package
import 'firebase_options.dart'; // Import the generated Firebase options

void main() async {
  // Ensure that the Flutter binding is initialized.
  // This is required to call platform channels before runApp.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the default options for the current platform.
  // The 'firebase_options.dart' file is generated by the 'flutterfire configure' command.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp( BazarioApp());
}

class BazarioApp extends StatelessWidget {
   BazarioApp({super.key});

  final _appRouter = AppRouter();

  @override
  Widget build(BuildContext context) {
    // Wrap the entire app with MultiProvider to make the HomeProvider
    // accessible throughout the entire app's widget tree.
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => HomeProvider()),
      ],
      child: MaterialApp.router(
        debugShowCheckedModeBanner: false,
        title: 'Bazario',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          fontFamily: 'Roboto',
        ),
        routerConfig: _appRouter.config(), // Provide the router configuration
      ),
    );
  }
}
